/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author fredd
 */
import java.awt.Color;
public class conversoruniversal1 extends javax.swing.JFrame {
private boolean modoOscuro = false;


    private Object jComboBox1;

    /**
     * Creates new form conversoruniversal1
     */
    public conversoruniversal1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        btnTema = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "longitud", "masa", "Temperatura", "volumen" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Metros", "Kilómetros", "Millas", "Pulgadas", "kilogramos", "libras", "gramos", "Celsius", "Fahrenheit", "Kelvin", "litros", "mililitros", "galones" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Metros", "Kilómetros", "Millas", "Pulgadas", "kilogramos", "libras", "gramos", "Celsius", "Fahrenheit", "Kelvin", "litros", "mililitros", "galones" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });

        jButton1.setText("calcular ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnTema.setText("Cambiar tema");
        btnTema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTemaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.Alignment.LEADING, 0, 86, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField2)
                            .addComponent(jComboBox3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addComponent(btnTema)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnTema)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(158, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
                                          

    String magnitud = (String) jComboBox1.getSelectedItem();

    // Limpiar origen y destino
    jComboBox2.removeAllItems();
    jComboBox3.removeAllItems();

    switch (magnitud) {

        case "longitud":
            jComboBox2.addItem("Metros");
            jComboBox2.addItem("Kilómetros");
            jComboBox2.addItem("Millas");
            jComboBox2.addItem("Pulgadas");

            jComboBox3.addItem("Metros");
            jComboBox3.addItem("Kilómetros");
            jComboBox3.addItem("Millas");
            jComboBox3.addItem("Pulgadas");
            break;

        case "masa":
            jComboBox2.addItem("kilogramos");
            jComboBox2.addItem("libras");
            jComboBox2.addItem("gramos");

            jComboBox3.addItem("kilogramos");
            jComboBox3.addItem("libras");
            jComboBox3.addItem("gramos");
            break;

        case "Temperatura": 
            jComboBox2.addItem("Celsius");
            jComboBox2.addItem("Fahrenheit");
            jComboBox2.addItem("Kelvin");

            jComboBox3.addItem("Celsius");
            jComboBox3.addItem("Fahrenheit");
            jComboBox3.addItem("Kelvin");
            break;

        case "volumen":
            jComboBox2.addItem("litros");
            jComboBox2.addItem("mililitros");
            jComboBox2.addItem("galones");

            jComboBox3.addItem("litros");
            jComboBox3.addItem("mililitros");
            jComboBox3.addItem("galones");
            break;
    }

    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
                                         
    String magnitud = (String) jComboBox1.getSelectedItem();
    String origen = (String) jComboBox2.getSelectedItem();
    String destino = (String) jComboBox3.getSelectedItem();

    // Validar número
    double valor;
    try {
        valor = Double.parseDouble(jTextField1.getText().trim());
    } catch (Exception e) {
        jTextField2.setText("");
        javax.swing.JOptionPane.showMessageDialog(this,
                "Valor no válido. Ingresa un número (usa punto para decimales).",
                "Error - entrada",
                javax.swing.JOptionPane.ERROR_MESSAGE);
        return;
    }

    double resultado = 0;

    try {

        // ===================== LONGITUD =====================
        if ("longitud".equals(magnitud)) {

            double metros = 0;

            // ORIGEN -> METROS
            if ("Metros".equals(origen)) {
                metros = valor;
            } else if ("Kilómetros".equals(origen)) {
                metros = valor * 1000;
            } else if ("Millas".equals(origen)) {
                metros = valor * 1609.34;
            } else if ("Pulgadas".equals(origen)) {
                metros = valor * 0.0254;
            } else {
                throw new Exception("Fórmula errónea (unidad origen)");
            }

            // METROS -> DESTINO
            if ("Metros".equals(destino)) {
                resultado = metros;
            } else if ("Kilómetros".equals(destino)) {
                resultado = metros / 1000.0;
            } else if ("Millas".equals(destino)) {
                resultado = metros / 1609.34;
            } else if ("Pulgadas".equals(destino)) {
                resultado = metros / 0.0254;
            } else {
                throw new Exception("Fórmula errónea (unidad destino)");
            }
        }

        // ===================== MASA =====================
        else if ("masa".equals(magnitud)) {

            double gramos = 0;

            if ("kilogramos".equals(origen)) {
                gramos = valor * 1000.0;
            } else if ("libras".equals(origen)) {
                gramos = valor * 453.592;
            } else if ("gramos".equals(origen)) {
                gramos = valor;
            } else {
                throw new Exception("Fórmula errónea (unidad origen)");
            }

            if ("kilogramos".equals(destino)) {
                resultado = gramos / 1000.0;
            } else if ("libras".equals(destino)) {
                resultado = gramos / 453.592;
            } else if ("gramos".equals(destino)) {
                resultado = gramos;
            } else {
                throw new Exception("Fórmula errónea (unidad destino)");
            }
        }

        // ===================== TEMPERATURA =====================
        else if ("Temperatura".equals(magnitud)) {

            double celsius = 0;

            if ("Celsius".equals(origen)) {
                celsius = valor;
            } else if ("Fahrenheit".equals(origen)) {
                celsius = (valor - 32.0) * 5.0 / 9.0;
            } else if ("Kelvin".equals(origen)) {
                celsius = valor - 273.15;
            } else {
                throw new Exception("Fórmula errónea (unidad origen)");
            }

            if ("Celsius".equals(destino)) {
                resultado = celsius;
            } else if ("Fahrenheit".equals(destino)) {
                resultado = (celsius * 9.0 / 5.0) + 32.0;
            } else if ("Kelvin".equals(destino)) {
                resultado = celsius + 273.15;
            } else {
                throw new Exception("Fórmula errónea (unidad destino)");
            }
        }

        // ===================== VOLUMEN =====================
        else if ("volumen".equals(magnitud)) {

            double ml = 0;

            if ("litros".equals(origen)) {
                ml = valor * 1000.0;
            } else if ("mililitros".equals(origen)) {
                ml = valor;
            } else if ("galones".equals(origen)) {
                ml = valor * 3785.41;
            } else {
                throw new Exception("Fórmula errónea (unidad origen)");
            }

            if ("litros".equals(destino)) {
                resultado = ml / 1000.0;
            } else if ("mililitros".equals(destino)) {
                resultado = ml;
            } else if ("galones".equals(destino)) {
                resultado = ml / 3785.41;
            } else {
                throw new Exception("Fórmula errónea (unidad destino)");
            }
        } else {
            throw new Exception("Magnitud desconocida");
        }

        // Mostrar resultado formateado (quitar ceros finales)
        String out = String.format("%.6f", resultado).replaceAll("\\.?0+$","");
        jTextField2.setText(out);

    } catch (Exception e) {
        // Mostrar ventana de error y limpiar resultado
        jTextField2.setText("");
        javax.swing.JOptionPane.showMessageDialog(this,
                "Conversión errónea: " + e.getMessage(),
                "Error - conversión",
                javax.swing.JOptionPane.ERROR_MESSAGE);
    }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void btnTemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTemaActionPerformed
                                     
    if (modoOscuro) {
        // Tema claro
        getContentPane().setBackground(Color.WHITE);

        jTextField1.setBackground(Color.WHITE);
        jTextField1.setForeground(Color.BLACK);

        jTextField2.setBackground(Color.WHITE);
        jTextField2.setForeground(Color.BLACK);

        jComboBox1.setBackground(Color.WHITE);
        jComboBox1.setForeground(Color.BLACK);

        jComboBox2.setBackground(Color.WHITE);
        jComboBox2.setForeground(Color.BLACK);

        jComboBox3.setBackground(Color.WHITE);
        jComboBox3.setForeground(Color.BLACK);

        jButton1.setBackground(Color.LIGHT_GRAY);
        jButton1.setForeground(Color.BLACK);

        btnTema.setBackground(Color.LIGHT_GRAY);
        btnTema.setForeground(Color.BLACK);

        modoOscuro = false;

    } else {
        // Tema oscuro
        getContentPane().setBackground(Color.BLACK);

        jTextField1.setBackground(Color.DARK_GRAY);
        jTextField1.setForeground(Color.WHITE);

        jTextField2.setBackground(Color.DARK_GRAY);
        jTextField2.setForeground(Color.WHITE);

        jComboBox1.setBackground(Color.DARK_GRAY);
        jComboBox1.setForeground(Color.WHITE);

        jComboBox2.setBackground(Color.DARK_GRAY);
        jComboBox2.setForeground(Color.WHITE);

        jComboBox3.setBackground(Color.DARK_GRAY);
        jComboBox3.setForeground(Color.WHITE);

        jButton1.setBackground(Color.GRAY);
        jButton1.setForeground(Color.WHITE);

        btnTema.setBackground(Color.GRAY);
        btnTema.setForeground(Color.WHITE);

        modoOscuro = true;
    }


    }//GEN-LAST:event_btnTemaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(conversoruniversal1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(conversoruniversal1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(conversoruniversal1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(conversoruniversal1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new conversoruniversal1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTema;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
